In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!pip install fg-data-profiling numpy pandas --quiet

from data_profiling import ProfileReport

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.5/400.5 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 18.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 2.6 MB/s eta 0:00:00

In [4]:
from google.colab import files

upload=files.upload()

Saving retail_sales_dataset_7500 (1).csv to retail_sales_dataset_7500 (1).csv

In [6]:
df=pd.read_csv('retail_sales_dataset_7500 (1).csv')

In [7]:
df.head()

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19

In [ ]:
profile=ProfileReport(df,title='Retail sales data',explorative=True)

profile.to_file('Retail sales data.html')

files.download('Retail sales data.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
 17%|█▋        | 2/12 [00:00<00:01,  6.36it/s]
 58%|█████▊    | 7/12 [00:00<00:00, 18.01it/s]
100%|██████████| 12/12 [00:00<00:00, 17.40it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date'],
      dtype='object')

In [9]:
df.dtypes

order_id              int64
customer_name        object
city                 object
region               object
category             object
product              object
sales               float64
discount_percent    float64
profit              float64
quantity              int64
payment_mode         object
order_date           object
dtype: object

# Month dataset clean

In [10]:
# order_date change to datetime
df['order_date']=pd.to_datetime(df['order_date'])

In [11]:
df.dtypes

order_id                     int64
customer_name               object
city                        object
region                      object
category                    object
product                     object
sales                      float64
discount_percent           float64
profit                     float64
quantity                     int64
payment_mode                object
order_date          datetime64[ns]
dtype: object

In [12]:
df['month_name']=df['order_date'].dt.month_name()

df['month_num']=df['order_date'].dt.month

df['quarter']=df['order_date'].dt.quarter

df['year']=df['order_date'].dt.year

In [13]:
df

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06,September,9,3,2025
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19,November,11,4,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,7496,Paul Lutz,Chennai,West,Sports,Football,31109.25,5.65,1868.70,2,Cash,2024-07-23,July,7,3,2024
7496,7497,Kristen Nichols,Chennai,North,Groceries,Milk,36463.95,12.81,6778.32,1,Cash,2025-01-22,January,1,1,2025
7497,7498,Brandon Adkins,Tirunelveli,North,Furniture,Chair,42692.31,10.00,4727.10,6,UPI,2024-09-27,September,9,3,2024
7498,7499,Karen Davidson,Madurai,South,Furniture,Chair,29658.17,21.13,5632.31,6,Card,2025-01-18,January,1,1,2025
7499,7500,Veronica Howell,Madurai,South,Electronics,Laptop,2912.79,1.75,357.65,2,Net Banking,2025-12-29,December,12,4,2025

# measure data

In [14]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date', 'month_name', 'month_num', 'quarter', 'year'],
      dtype='object')

In [15]:
# Total customer

total_customer =df['customer_name'].nunique()

print("Total Customer : ",total_customer)

Total Customer :  7128

In [16]:
# Total sales

total_sales=round(df['sales'].sum(),2)

print("Total sales :",total_sales)

Total sales : 188546725.57

In [17]:
# Average Profit

avg_profit = round(df['profit'].mean(),2)

print('averge profit : ', avg_profit)

averge profit :  3784.64

In [18]:
# Region wise sales

region_wise_sales=df.groupby('region')['sales'].sum()

print('Region wise sales: ', region_wise_sales)

Region wise sales:  region
East     47065554.03
North    48449603.86
South    47698472.27
West     45333095.41
Name: sales, dtype: float64

In [19]:
# Top 5 Product

df['product'].unique()

print('Top 5 product')

top_5_product=(df.groupby('product')['sales'].sum().sort_values(ascending=False).head(5))

# top_5_product=(df.groupby(['category','product'])['sales'].sum().sort_values(ascending=False).head(5))

print('Top 5 product : ',top_5_product)

Top 5 product
Top 5 product :  product
Cricket Bat    10627356.95
Cupboard       10176026.11
Table          10118540.19
Mobile          9779948.59
Jeans           9738303.64
Name: sales, dtype: float64

In [20]:
# city by sales

city_by_sales = df.groupby('city')['sales'].sum().sort_values(ascending=False)

print('city by sales : ',city_by_sales)

city by sales :  city
Chennai        32239086.17
Madurai        31840609.98
Salem          31582831.27
Trichy         31143733.44
Coimbatore     31080424.69
Tirunelveli    30660040.02
Name: sales, dtype: float64

In [21]:
# high and low sales in month

high_sales_month=df.groupby('month_name')['sales'].sum().sort_values(ascending=False).head(5)
print('high_sales_month : ', high_sales_month)

print('\n')

low_sales_month=df.groupby('month_name')['sales'].sum().sort_values(ascending=True).head(5)
print('low_sales_month : ', low_sales_month)

high_sales_month :  month_name
July         17594195.43
August       16350247.20
January      16258986.02
September    16230404.28
November     16078242.30
Name: sales, dtype: float64


low_sales_month :  month_name
May         14736524.03
February    14766210.95
June        14781566.94
April       14823078.83
March       15235777.61
Name: sales, dtype: float64

In [22]:
# Product quantity count

product_quantity_count=df.groupby('product')['quantity'].count().sort_values(ascending=False)

print('Product quantity count : ',product_quantity_count)

Product quantity count :  product
Cricket Bat    415
Table          407
Mobile         400
T-Shirt        389
Kurti          387
Jeans          386
Rice           386
Cupboard       385
Sofa           377
Jacket         375
Laptop         375
Chair          372
Football       364
Snacks         360
Headphones     360
Milk           359
Oil            356
Gym Bag        355
Shoes          347
Smart Watch    345
Name: quantity, dtype: int64

# Data visualization

In [23]:
pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)

In [24]:
df

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06,September,9,3,2025
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19,November,11,4,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,7496,Paul Lutz,Chennai,West,Sports,Football,31109.25,5.65,1868.70,2,Cash,2024-07-23,July,7,3,2024
7496,7497,Kristen Nichols,Chennai,North,Groceries,Milk,36463.95,12.81,6778.32,1,Cash,2025-01-22,January,1,1,2025
7497,7498,Brandon Adkins,Tirunelveli,North,Furniture,Chair,42692.31,10.00,4727.10,6,UPI,2024-09-27,September,9,3,2024
7498,7499,Karen Davidson,Madurai,South,Furniture,Chair,29658.17,21.13,5632.31,6,Card,2025-01-18,January,1,1,2025
7499,7500,Veronica Howell,Madurai,South,Electronics,Laptop,2912.79,1.75,357.65,2,Net Banking,2025-12-29,December,12,4,2025

In [29]:
# as_index=True   → grouped column becomes index
# as_index=False  → grouped column stays as column

sales_month = (
    df.groupby(
        ['month_num', 'month_name'],
        as_index=False
    )['sales']
    .sum()
    .sort_values('month_num')
)
print('sales_month : ', sales_month)

fig=px.line(sales_month,x='month_name',y='sales',title='monthly sales',labels={'month_name':'Month','sales':'Total Sales'},color_discrete_sequence=['#5d9854'])

fig.show()

sales_month :      month_num month_name        sales
0           1    January  16258986.02
1           2   February  14766210.95
2           3      March  15235777.61
3           4      April  14823078.83
4           5        May  14736524.03
5           6       June  14781566.94
6           7       July  17594195.43
7           8     August  16350247.20
8           9  September  16230404.28
9          10    October  15800768.35
10         11   November  16078242.30
11         12   December  15890723.63

In [27]:
import plotly.express as px

top5 = (
    df.groupby('product', as_index=False)['quantity']
      .sum()
      .sort_values('quantity', ascending=False)
      .head(5)
)

fig = px.bar(
    top5,
    x='product',
    y='quantity',
    title='Top 5 Products by Quantity',
    labels={
        'product': 'Product Name',
        'quantity': 'Total Quantity'
    },
    color_discrete_sequence=['blue']
)

fig.update_layout(
    plot_bgcolor='lightgray',
    paper_bgcolor='white',
    xaxis_title='Product Name',
    yaxis_title='Total Quantity'
)

fig.show()

In [34]:
# Sales by Category




fig=px.pie(df,values='sales',names='category',title='sales by category')

fig.show()

In [36]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date', 'month_name', 'month_num', 'quarter', 'year'],
      dtype='object')

In [37]:
# Profit vs Discount

fig=px.scatter(df,x='profit',y='discount_percent',title='Profit vs Discount')

fig.show()

In [44]:
# Sales distribution

fig=px.histogram(df,x='sales',title='Sales distribution')

fig.update_traces(
    xbins=dict(size=15)
)

fig.show()

In [39]:
# Outlier analysis

fig=px.box(df,x='category',y='sales',title='Outlier analysis')

fig.show()

In [42]:
fig=px.treemap(df,path=['category','product'],values='sales',title='sales hierarchy')

fig.show()

In [45]:
city_coordinates = {
    'Chennai': (13.0827, 80.2707),
    'Madurai': (9.9252, 78.1198),
    'Salem': (11.6643, 78.1460),
    'Trichy': (10.7905, 78.7047),
    'Coimbatore': (11.0168, 76.9558),
    'Tirunelveli': (8.7139, 77.7567)
}

df['latitude'] = df['city'].map(lambda x: city_coordinates[x][0])
df['longitude'] = df['city'].map(lambda x: city_coordinates[x][1])

In [46]:
df

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year,latitude,longitude
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024,10.7905,78.7047
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024,13.0827,80.2707
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024,9.9252,78.1198
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06,September,9,3,2025,9.9252,78.1198
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19,November,11,4,2024,9.9252,78.1198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,7496,Paul Lutz,Chennai,West,Sports,Football,31109.25,5.65,1868.70,2,Cash,2024-07-23,July,7,3,2024,13.0827,80.2707
7496,7497,Kristen Nichols,Chennai,North,Groceries,Milk,36463.95,12.81,6778.32,1,Cash,2025-01-22,January,1,1,2025,13.0827,80.2707
7497,7498,Brandon Adkins,Tirunelveli,North,Furniture,Chair,42692.31,10.00,4727.10,6,UPI,2024-09-27,September,9,3,2024,8.7139,77.7567
7498,7499,Karen Davidson,Madurai,South,Furniture,Chair,29658.17,21.13,5632.31,6,Card,2025-01-18,January,1,1,2025,9.9252,78.1198
7499,7500,Veronica Howell,Madurai,South,Electronics,Laptop,2912.79,1.75,357.65,2,Net Banking,2025-12-29,December,12,4,2025,9.9252,78.1198

In [52]:
city_sales=(df.groupby(['city','latitude','longitude'],as_index=False)['sales'].sum())


fig=px.scatter_map(city_sales,lat='latitude',lon='longitude',size='sales',color='sales',hover_name='city',title='city wise sales',zoom=5)

fig.show()

In [57]:
category_sales = (
    df.groupby(['category', 'product'], as_index=False)['sales']
      .sum()
)

fig = px.sunburst(
    category_sales,
    path=['category', 'product'],
    values='sales',
    title='Sales Distribution by Category& Product'
)

fig.show()

In [60]:
df.to_csv('clean_retail_dataset',index=False)